config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # User
  devise_for :users
  resources :users, :only => [:index, :show, :update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # Tweet
  root to: 'tweets#index'
  resources :tweets
  # follow
  resources :users do
    member do
     get :following, :followers, :user_tweets
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "following_tweets" => "tweets#following_tweets"
  # Teamroom
  get 'rooms/show'

end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user, optional: true
    # mount_uploader :video, VideoUploader
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.page(params[:page]).reverse_order
  end

  def show
  end

  def new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.save
    redirect_to root_path
  end

  def following_tweets
    @tweet = Tweet.new
    @user = current_user
    @users = @user.followings.order("created_at DESC").page(params[:page]).per(10)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:user_id, :content)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/following_tweets.html.erb
<div class = "col-md-4">
  <h2>フォロー中の募集一覧</h2>
    <div class = "jumbotron mt-4">
      <%= form_for @tweet do |f| %>
        <%= f.text_area :content, class:"form-control" %>
        <%= f.hidden_field :user_id, value:current_user.id %>
        <%= f.submit '募集する', class:"btn btn-primary bosyu" %>
      <% end %>
    </div>
  <% @users.each do |user| %>
    <% @tweets = Tweet.where(user_id: user.id).limit(1).order("created_at DESC") %>
      <% @tweets.each do |tweet| %>
        <div class ="jumbotron mt-2">
        <p><%= tweet.created_at.strftime('%Y/%m/%d') %></p>
        <p><%= attachment_image_tag tweet.user, :profile_image, format: 'jpeg', class:"attachment user profile_image", fallback: "no_image.jpg", size:"40x40" %>
        <%= link_to tweet.user.name, user_path(tweet.user) %></p>
        <p><%= tweet.content %></p>
      </div>
      <% end %>
  <% end %>
    <%= paginate(@users) %>
</div>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
<div class = "col-md-4">
  <h2>ゲーム募集しよう！</h2>
  <div class = "jumbotron mt-4">
    <%= form_for @tweet do |f| %>
      <%= f.text_area :content, class:"form-control" %>
      <%= f.hidden_field :user_id, value:current_user.id %>
      <%= f.submit '募集する', class:"btn btn-primary bosyu" %>
    <% end %>
  </div>
  <% @tweets.each do |tweet| %>
    <div class ="jumbotron mt-2">
      <p><%= tweet.created_at.strftime('%Y/%m/%d') %></p>
      <p><%= attachment_image_tag tweet.user, :profile_image, format: 'jpeg', class:"attachment user profile_image", fallback: "no_image.jpg", size:"40x40" %>
      <%= link_to tweet.user.name, user_path(tweet.user) %></p>
      <p><%= tweet.content %></p>
    </div>
  <% end %>
  <%= paginate @tweets, class: "paginate" %>
  <%= link_to 'フォロー中のツイート一覧へ', following_tweets_path, {class: 'btn btn-primary withripple' }%>

</div>

<% else %>
    <div class ="container home">
      <div class="row1">
			  <div class="col-md-12">
            <h1><strong>最高の仲間を探そう。</strong></h1>
          <p>
            <%= link_to "ログイン", new_user_session_path, class:"btn btn-info" %>
          
            <%= link_to "新規登録", new_user_registration_path, class:"btn btn-success" %>
          </p>
          </div>
      </div>
    </div>
<% end %>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>