config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # User
  devise_for :users
  resources :users, :only => [:index, :show, :update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # Tweet
  root to: 'tweets#index'
  resources :tweets
  # follow
  resources :users do
    member do
     get :following, :followers, :user_tweets
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "following_tweets" => "tweets#following_tweets"
  # Teamroom
  get 'rooms/show'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :tweets, dependent: :destroy
  attachment :profile_image
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships
        
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
        
  has_many :followers, through: :follower_relationships
        
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end
        
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end
        
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]
  def index
    @users=User.all
  end

  def show
    #@user = User.find_by(:username => params[:username])
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
		if @user.update(user_params)
       redirect_to user_path(@user.id)
       
		else
		   render :edit
		end
  end
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
  private
  def user_params
		params.require(:user).permit(:name, :profile_image, :location, :about)
	end
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
     end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %> 

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large btn-warning follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-8">
        <h2>User Edit</h2>
		<%= form_for(@user) do |f| %>
		<div class="field">
			<label for="user_name">表示名</label>
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<label for="user_image">プロフィール画像</label>
			<%= f.attachment_field :profile_image %>
		</div>
        <div class="field">
			<label for="user_introduction">location：</label>
			<%= f.text_field :location, autofocus: true %>
		</div>
		<div class="field">
			<label for="user_introduction">About：</label>
			<%= f.text_field :about, autofocus: true %>
		</div>
		<div class="actions">
			<%= f.submit "Update", class:"btn btn-success" %>
		</div>
		<% end %>
</div>

app/views/users/index.html.erb
<div class = "col-md-4">  
  <h1>全てのユーザー</h1>
  <% if user_signed_in? %>
    <% @users.each do |u| %>
    <p><%= attachment_image_tag u, :profile_image, format: 'jpeg', class:"attachment user profile_image", fallback: "no_image.jpg", size:"40x40" %>
    <a href="/users/<%= u.id %>"><%= u.name %></a></p>
    <hr>
    <% end %>
  <% else %>
    <%= link_to "ユーザーを登録する", new_user_registration_path %>
    <br>
    <%= link_to "ログインする", new_user_session_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class ="col-md-8">
  <p>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
     <% if current_user == @user %>
    <span class = "edituser"><%= link_to "Edit", edit_user_path(current_user.id), class:"btn btn-success" %></span>
    <% end %>
  </p>
  <p>
    <h1><%= @user[:name] %></h1>
  </p>
  <p>@<%= @user[:username] %></p>
  <ul>
      <li>Location : <%= @user[:location] %></li>
      <li>About   : <%= @user[:about] %></li>
  </ul>
  <p>
    <%= render 'follow_form' %>
    <%= render 'stats' %>
  </p>

  <% if @user.id == current_user.id %>

  <% else %>
    <% if @isRoom == true %>
      <p><a href="/rooms/<%= @roomId %>" class="btn btn-success">チャットへ</a>
    <% else %>
      <%= form_for @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, :value=> @user.id %>
        <% end %>
        <p><%= f.submit "チャットを始める", class:"btn btn-success" %>
      <% end %>
    <% end %>
  <% end %>

  <%= link_to "募集一覧に戻る", root_path, class:"btn btn-secondary" %></p>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>