config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # User
  devise_for :users
  resources :users, :only => [:index, :show, :update]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  # Tweet
  root to: 'tweets#index'
  resources :tweets
  # follow
  resources :users do
    member do
     get :following, :followers, :user_tweets
    end
  end
  resources :relationships, only: [:create, :destroy]
  get "following_tweets" => "tweets#following_tweets"
  # Teamroom
  get 'rooms/show'

end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
  
  def index
    @currentEntries = current_user.entries
    myRoomIds = []
  
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
  
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',@user.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<% @anotherEntries.each do |e| %>
  <%= link_to room_path(e.room.id) do %>
    <%= e.user.name %>とのDM<br>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<div class = "col-md-4"> 
    <h1>個別メッセージ</h1>

    <h4>参加者</h4>
    <% @entries.each do |e| %>
      <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.name %> さん</a></strong></h5>
    <% end %>

    <hr>
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <strong><%= m.content %></strong>
        <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.name %> さん</a></strong></small>
        <hr>
      <% end %>
    <% else %>
      <h3 class="text-center">メッセージはまだありません</h3>
    <% end %>
 <div class = "jumbotron mt-4">
    <%= form_for @message do |f| %>
      <%= f.text_area :content, class:"form-control", :placeholder => "メッセージを入力して下さい" %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <br>
      <p class = "chatsubmit"><%= f.submit "投稿する" %></p>
    <% end %>
  </div>

    <p class = "backhome"><%= link_to "HOMEに戻る", root_path %></p>
</div>